import {useState,useEffect,useMemo,useRef} from 'react';
import {LayoutGrid,UserRound,Skull,Box,TriangleAlert,Star,KeyRound,Zap,Rocket,Leaf,Mountain,Monitor,Music,Search,Package,Maximize,Minimize,HelpCircle,Menu,X,ChevronUp,ChevronLeft,ChevronRight,Check,Plus} from 'lucide-react';
import AssetCard from './components/AssetCard';
import AssetDialog from './components/AssetDialog';
import Basket from './components/Basket';
import ImportHelp from './components/ImportHelp';
import {filterAssets,parseSelection,selectionText,safeName} from './data.mjs';
import {downloadFile,downloadPackage,saveBlob} from './downloads.mjs';
const icons={all:LayoutGrid,players:UserRound,enemies:Skull,ground:Box,hazards:TriangleAlert,collectables:Star,endpoints:KeyRound,powerups:Zap,projectiles:Rocket,decorations:Leaf,backgrounds:Mountain,interface:Monitor,audio:Music};
const labels={players:'Player',enemies:'Enemy',ground:'Ground',hazards:'Hazard',collectables:'Collectable',endpoints:'Exit',powerups:'Power-up',projectiles:'Projectile',decorations:'Decoration',backgrounds:'Background',interface:'Interface',audio:'Audio'};
const blankFilters={category:'all',query:'',theme:'',environment:'',movement:''};
function loadSaved(){try{const x=JSON.parse(localStorage.getItem('game-forge-selection-v1'));return x?.schemaVersion===1&&Array.isArray(x.ids)?x:{ids:[],name:'My Game Forge assets'};}catch{return {ids:[],name:'My Game Forge assets'};}}
function loadColumns(){try{const n=Number(localStorage.getItem('game-forge-columns-v1'));return [4,6,8].includes(n)?n:4;}catch{return 4;}}
export default function App(){
 const [columns,setColumns]=useState(loadColumns);
 useEffect(()=>{try{localStorage.setItem('game-forge-columns-v1',String(columns));}catch{}},[columns]);
 const [catalogue,setCatalogue]=useState(null),[error,setError]=useState('');const [saved]=useState(loadSaved);
 const [ids,setIds]=useState(()=>new Set(saved.ids)),[name,setName]=useState(saved.name),[basket,setBasket]=useState(false),[nav,setNav]=useState(false),[detail,setDetail]=useState(null),[help,setHelp]=useState(false),[notes,setNotes]=useState(true);
 const [filters,setFilters]=useState(blankFilters),[sort,setSort]=useState('featured'),[page,setPage]=useState(1),[multi,setMulti]=useState(false),[toast,setToast]=useState(''),[progress,setProgress]=useState(null),[fullscreen,setFullscreen]=useState(false);
 const toastTimer=useRef(null),abort=useRef(null),gridRef=useRef(null),storageWarning=useRef(false);
 const notify=message=>{setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),7000);};
 useEffect(()=>{const controller=new AbortController();fetch('catalogue.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error(`Catalogue request failed (${r.status})`);return r.json();}).then(data=>{if(data.schemaVersion!==1||!Array.isArray(data.assets))throw Error('Unsupported catalogue');setCatalogue(data);const known=new Set(data.assets.map(a=>a.id));setIds(prev=>new Set([...prev].filter(id=>known.has(id))));}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
 useEffect(()=>{if(!catalogue)return;try{localStorage.setItem('game-forge-selection-v1',selectionText(ids,name));}catch{if(!storageWarning.current){storageWarning.current=true;notify('This browser cannot remember your basket. Use Save selection before leaving.');}}},[ids,name,catalogue]);
 useEffect(()=>{const fn=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',fn);return()=>document.removeEventListener('fullscreenchange',fn);},[]);
 useEffect(()=>()=>{clearTimeout(toastTimer.current);abort.current?.abort();},[]);
 const all=catalogue?.assets||[];const categories=catalogue?.categories||[];
 const selected=useMemo(()=>all.filter(a=>ids.has(a.id)),[all,ids]);
 const themes=useMemo(()=>[...new Set(all.flatMap(a=>a.themes))].sort(),[all]);const environments=useMemo(()=>[...new Set(all.flatMap(a=>a.environments))].sort(),[all]);
 const results=useMemo(()=>{const r=filterAssets(all,filters);return sort==='name'?r.toSorted((a,b)=>a.name.localeCompare(b.name,'en-GB')):sort==='newest'?r.toSorted((a,b)=>b.batch-a.batch):r;},[all,filters,sort]);
 const setFilter=(key,value)=>{setFilters(f=>({...f,[key]:value}));setPage(1);};
 const perPage=24,pages=Math.max(1,Math.ceil(results.length/perPage));const visible=results.slice((page-1)*perPage,page*perPage);
 const toggle=id=>{if(progress){notify('Wait for the current download or cancel it before changing the package.');return;}setIds(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next;});};
 const addMany=assets=>{setIds(prev=>new Set([...prev,...assets.map(a=>a.id)]));notify(`${assets.length} assets added. Existing selections kept without duplicates.`);};
 const individual=async file=>{notify(`Downloading ${file.name}…`);try{await downloadFile(file);notify(`${file.name} downloaded.`);}catch(e){notify(e.message);}};
 const download=async()=>{abort.current=new AbortController();try{await downloadPackage(selected,name,notes,setProgress,abort.current.signal);notify('Your package is ready. Extract the ZIP before importing.');}catch(e){abort.current.abort();notify(e.name==='AbortError'?'Download cancelled. Your basket is saved.':e.message);}finally{setProgress(null);}};
 const load=async file=>{try{if(file.size>2*1024*1024)throw Error('Selection file is too large. Choose a Game Forge selection JSON file.');const x=parseSelection(await file.text(),new Set(all.map(a=>a.id)));setIds(new Set(x.ids));setName(x.name);notify(`Loaded ${x.ids.length} assets.${x.missing.length?` ${x.missing.length} unavailable assets were skipped.`:''}`);}catch(e){notify(e.message);}};
 const full=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('Fullscreen is unavailable in this browser window.');}};
 const categoryName=filters.category==='all'?'All assets':categories.find(c=>c.id===filters.category)?.label;
 const filtered=filters.category!=='all'||filters.query||filters.theme||filters.environment||filters.movement;
 if(error)return <main className="load-state"><h1>Game Forge could not load</h1><p>{error}</p><button className="gold" onClick={()=>location.reload()}>Try again</button></main>;
 if(!catalogue)return <main className="load-state"><img src="brand/level-lab.png" alt="Level Lab"/><h1>Opening Game Forge…</h1><p>Getting your asset library ready.</p></main>;
 return <div className={`app ${basket?'basket-open':''} ${nav?'nav-open':''}`} data-density={columns} style={{'--preferred-columns':columns}}>
  <a href="#asset-results" className="skip-link">Skip to assets</a>
  {nav&&<button className="nav-shade" onClick={()=>setNav(false)} aria-label="Close categories"/>}
  <aside className="sidebar" aria-label="Asset categories"><div className="brand"><img src="brand/level-lab.png" alt="Level Lab"/><button className="mobile-close icon-button" onClick={()=>setNav(false)} aria-label="Close category menu"><X/></button></div><div className="sidebar-label">ASSET LIBRARY</div>
   <nav>{[{id:'all',label:'All assets',count:all.length},...categories].map(cat=>{const Icon=icons[cat.id]||Box;return <button key={cat.id} className={filters.category===cat.id?'active':''} onClick={()=>{setFilter('category',cat.id);setNav(false);}} aria-current={filters.category===cat.id?'page':undefined}><Icon/><span>{cat.label}</span><small>{cat.count}</small></button>;})}</nav>
   <div className="sidebar-art" aria-hidden="true"/>
  </aside>
  <header className="topbar"><button className="mobile-menu icon-button" onClick={()=>setNav(!nav)} aria-label="Open category menu"><Menu/></button><div className="breadcrumb"><Box/><strong>LEVEL LAB</strong><span>/</span><b>GAME FORGE</b></div><div className="top-actions"><button className="help-button" onClick={()=>setHelp(true)}><HelpCircle/><span>Import help</span></button><button className="icon-button fullscreen" onClick={full} aria-label={fullscreen?'Exit fullscreen':'Enter fullscreen'}>{fullscreen?<Minimize/>:<Maximize/>}</button><button className="package-button" onClick={()=>setBasket(!basket)} aria-expanded={basket}><Package/><span>My package</span><b>{selected.length}</b></button></div></header>
  <main className="main"><div className="hero"><h1>Choose your assets. Build your own story.</h1><p>{all.length.toLocaleString('en-GB')} assets to mix, match and make your own.</p><div className="filters"><label className="search"><Search/><input type="search" aria-label="Search assets" placeholder="Search assets, characters, places…" value={filters.query} onChange={e=>setFilter('query',e.target.value)}/></label><div className="filter-row"><label><span className="sr-only">Theme</span><select aria-label="Theme" value={filters.theme} onChange={e=>setFilter('theme',e.target.value)}><option value="">Theme</option>{themes.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="sr-only">Environment</span><select aria-label="Environment" value={filters.environment} onChange={e=>setFilter('environment',e.target.value)}><option value="">Environment</option>{environments.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="sr-only">Movement</span><select aria-label="Movement" value={filters.movement} onChange={e=>setFilter('movement',e.target.value)}><option value="">Movement</option><option value="animated">Animated</option><option value="static">Static</option><option value="quadruped">Four-legged</option><option value="float">Floating</option><option value="fly">Flying</option></select></label><button className="text-button" onClick={()=>{setFilters(blankFilters);setPage(1);}}>Clear filters</button></div></div></div>
   <section id="asset-results" ref={gridRef} className="results" aria-labelledby="results-heading"><div className="results-toolbar"><div className="results-title"><h2 id="results-heading">{categoryName}</h2><span aria-live="polite">{results.length.toLocaleString('en-GB')} assets</span></div><div className="results-actions">{filtered?<button className="outline-gold" disabled={!results.length||!!progress} onClick={()=>addMany(results)}><Package/>Add {results.length} {filters.query||filters.theme||filters.environment||filters.movement?'matches':'assets'}</button>:<button className="outline-gold" disabled={!!progress} onClick={()=>setMulti(!multi)} aria-pressed={multi}><Package/>{multi?'Done selecting':'Select multiple'}</button>}<label className="sort">Sort:<select aria-label="Sort assets" value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="featured">Featured</option><option value="name">Name A–Z</option><option value="newest">Newest batch</option></select></label></div></div>
    <div className="view-controls"><span>Preview size</span><div className="column-options" role="group" aria-label="Cards per row">{[4,6,8].map(n=><button key={n} aria-pressed={columns===n} aria-label={`${n} cards per row`} title={`${n} per row on wide screens; automatically fits smaller screens`} onClick={()=>setColumns(n)}>{n}</button>)}</div><span className="view-hint">per row · fits your screen</span></div>
    {multi&&!filtered&&<div className="multi-bar"><span>Add a page at a time, or choose cards individually.</span><button disabled={!!progress} onClick={()=>addMany(visible)}><Plus/>Add these {visible.length} assets</button></div>}
    {visible.length?<div className="asset-grid">{visible.map(asset=><AssetCard key={asset.id} asset={asset} selected={ids.has(asset.id)} onToggle={toggle} onOpen={setDetail} onDownload={individual} label={labels[asset.category]}/>)}</div>:<div className="empty-results"><Search/><h3>No assets found</h3><p>Try a broader search or clear a filter.</p><button onClick={()=>{setFilters(blankFilters);setPage(1);}}>Clear filters</button></div>}
    <div className="pagination"><span>{results.length?`${(page-1)*perPage+1}–${Math.min(page*perPage,results.length)} of ${results.length.toLocaleString('en-GB')}`:'0 results'}</span><div><button disabled={page===1} onClick={()=>{setPage(p=>p-1);gridRef.current?.scrollIntoView({block:'start'});}} aria-label="Previous page"><ChevronLeft/></button><span>Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>{setPage(p=>p+1);gridRef.current?.scrollIntoView({block:'start'});}} aria-label="Next page"><ChevronRight/></button></div></div>
   </section>
  </main>
  {basket?<Basket assets={selected} categories={categories} name={name} setName={setName} onClose={()=>setBasket(false)} onRemove={toggle} onClear={()=>{if(window.confirm('Remove all assets from your package?'))setIds(new Set());}} onDownload={download} onSave={()=>saveBlob(new Blob([selectionText(ids,name)],{type:'application/json'}),safeName(name)+'-selection.json')} onLoad={load} notes={notes} setNotes={setNotes} progress={progress} onCancel={()=>abort.current?.abort()}/>:<button className="basket-collapsed" onClick={()=>setBasket(true)} aria-expanded="false"><Package/><strong>My package · {selected.length} assets</strong><ChevronUp/><span>Review</span></button>}
  {detail&&<AssetDialog key={detail.id} asset={detail} selected={ids.has(detail.id)} onClose={()=>setDetail(null)} onToggle={toggle} onDownload={individual}/>}
  {help&&<ImportHelp onClose={()=>setHelp(false)}/>}
  {toast&&<div className="toast" role="status"><span>{toast}</span><button onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={18}/></button></div>}
 </div>;
}
