import {useRef} from 'react';
import {Package,ChevronDown,Download,X,Save,FolderOpen,Trash2} from 'lucide-react';
import {defaultFiles,formatBytes,fileDescription} from '../data.mjs';
export default function Basket({assets,categories,name,setName,onClose,onRemove,onClear,onDownload,onSave,onLoad,notes,setNotes,progress,onCancel}){
 const fileInput=useRef(null);const files=defaultFiles(assets);const bytes=files.reduce((n,f)=>n+f.bytes,0);
 return <aside className="basket" aria-label="My package"><div className="basket-heading"><h2><Package/>My package <span className="count">{assets.length}</span></h2><button className="icon-button" onClick={onClose} aria-label="Collapse package"><ChevronDown/></button></div>
  <p className="basket-intro">Mix assets from any category.</p><label className="package-name">Package name<input maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="My Game Forge assets"/></label>
  <div className="basket-items">{assets.length===0?<div className="empty-basket"><Package/><h3>Your story starts here</h3><p>Add characters, places and objects to build your own package.</p></div>:categories.map(cat=>{const group=assets.filter(a=>a.category===cat.id);return group.length?<section key={cat.id}><h3>{cat.label} <span>{group.length}</span></h3>{group.map(a=><div className="basket-row" key={a.id}><button className="basket-thumb" tabIndex={-1} aria-hidden="true">{a.primary.thumbnail?<img src={a.primary.thumbnail} alt=""/>:<span>♫</span>}</button><div><strong>{a.name}</strong><span>{fileDescription(a.primary)}</span>{a.defaultFiles.length>1&&<span>{a.defaultFiles.length} files included</span>}</div><button className="remove icon-button" disabled={!!progress} onClick={()=>onRemove(a.id)} aria-label={`Remove ${a.name}`}><X/></button></div>)}</section>:null;})}</div>
  <footer className="basket-footer"><div className="package-total"><strong>{assets.length} assets selected</strong><span>{files.length} files · {formatBytes(bytes)}</span></div><p className="small muted">GameMaker filenames preserved</p><label className="checkbox"><input type="checkbox" checked={notes} onChange={e=>setNotes(e.target.checked)}/>Include import notes</label>
   <div className="selection-actions"><button onClick={onSave} disabled={!assets.length}><Save/>Save selection</button><button onClick={()=>fileInput.current.click()} disabled={!!progress}><FolderOpen/>Load selection</button><input ref={fileInput} type="file" accept="application/json,.json" hidden onChange={e=>{if(e.target.files[0])onLoad(e.target.files[0]);e.target.value='';}}/></div>
   {progress?<div className="download-progress" role="status"><p>{progress.phase} · {progress.done} / {progress.total}</p><progress max={progress.total} value={progress.done}/><button onClick={onCancel}>Cancel download</button></div>:<button className="gold download-package" onClick={onDownload} disabled={!assets.length}><Download/>Download package (.zip)</button>}
   <button className="clear-package" onClick={onClear} disabled={!assets.length||!!progress}><Trash2/>Clear package</button>
  </footer></aside>;
}
